### ISSUE TITLE
Change comment to comment calling comment_impl

### ISSUE THREAD

**Issue by MondayPM** [andyli/CommentString#1]
I would like to change comment to the following in order to use my own utility function that is something like:

```
public static function comment_impl(transforms:Array<ExprOf<String->String>>,pos):ExprOf<String> {
    var str = File.getContent(Context.resolvePath(pos.file)).substring(pos.max);
    var cms = try {
        readComments(str, pos.max);
    } catch (e:Dynamic) {
        Context.error(e, Context.currentPos());
    }

    if (cms.length == 0)
        Context.error("No comment was found.", Context.currentPos());

    var exprs = [for (l in cms) {
        var pos = Context.makePosition({ file: pos.file, min: l.min, max: l.min + l.str.length});
        macro @:pos(pos) $v{l.str};
    }];
    var expr = exprs.slice(1).fold(function(l, e) {
        return macro $e + $l;
    }, exprs[0]);

    while (transforms.length > 0) {
        var t = transforms.shift();
        expr = macro @:pos(t.pos) $t($expr);
    }

    return expr;
}
macro static public function comment(transforms:Array<ExprOf<String->String>>):ExprOf<String> {
    var pos:Context.getPosInfos(Context.currentPos());
    return comment_impl(transforms,pos);
}
```

My utility function:

```
macro public static function bq():ExprOf<String> {
    return CommentString.comment_impl(format,unindent,Context.currentPos());
}
```

I thought the above would work but it obviously does not. I don't understand how format (and unindent) are getting ExprOf<String> as input in a call such as comment(format). I can't tell if is even calling format as a macro function which generates ExprOf<String->String> to be passed to comment, or is the identifier format being passed to comment (ie is format vs format() a macro call?).

If format is being called by the expression comment(format) I don't know how it's getting the comment string. If it's not being called, I don't understand how the function signature of transforms is 

```
[ExprOf<String->String>] as opposed to [ExprOf<FunctionNameIdentifier>] (psuedocode)
```

Either way, it would be nice to have a shorthand version as specified.

**Comment by MondayPM** [comment]
Regardless of the provision of this type of shorthand, it would be really nice to understand what is going on with the transformation of type signature of `format` to `ExprOf<String->String>` provided to `transformations`.

**Comment by andyli** [comment]
The transformers are really called.

To create your utility function, try this:

``` haxe
import comments.CommentString.*;

class Test {
    macro static function bq(s:ExprOf<String>):ExprOf<String> {
        return macro unindent(format($s));
    }

    static function main():Void {
        var name = "John";
        var age = 33;
        var str = comment(bq) /**
            My name is <strong>$name</strong> and I'm <em>$age</em> years old.
        **/;
        trace(str);
    }
}
```

The gotcha is that, `format` is a macro function that takes a string literal, or an expression that can be resolved to a `String` **at compile time**. That means the utility function has to be a macro function, or else `format` wouldn't be able to get the input at compile time.

If we don't need `format`, a normal `String->String` will work as expected:

``` haxe
import comments.CommentString.*;

class Test {
    static function main():Void {
        function up(s:String) return s.toUpperCase();
        var str = comment(unindent, up) /**
            testing
        **/;
        trace(str); //TESTING
    }
}
```

**Comment by MetaChrome** [comment]
I am going to try to do this myself to learn simultaneously to get caught up with macro reification. What I wanted was:

```bq = comment(unindent,format)``` not  bq=unindent,format

bq stands for both quotes ;)

**Comment by MondayPM** [comment]
```
macro public static function bq():ExprOf<String> {
    return comments.CommentString.comment_impl([macro comments.CommentString.unindent,macro comments.CommentString.format],Context.getPosInfos(Context.currentPos()));
}
```

I do hope you seperate comment into comment_impl to facilitate the above utility functionality

**Comment by MetaChrome** [comment]
The above does not execute unindent in the macro context instead generating:

comments_StringTransform.unindent

**Comment by andyli** [comment]
Sorry for the late reply. I have been busy for wwx and other stuffs.

In fact, the `bq()` function can be implemented without any modification to the CommentString lib:

``` haxe
class Test {
    macro static function bq() {
        var pos = haxe.macro.Context.currentPos();
        return macro  @:pos(pos) comments.CommentString.comment(
            comments.CommentString.unindent,
            comments.CommentString.format
        );
    }
    static function main() {
        var str = bq()/**
            testing!!
        **/;
        trace(str); //testing!!
    }
}
```

**Comment by andyli** [comment]
Closing for now. Feel free to open another issue if you've any other problem :)
